
server:
  port: 8769

spring:
  profiles: eureka2
eureka:
  instance:
    hostname: eureka2
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/
